# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
## see https://hexo.io/zh-cn/docs/configuration.html

# Site
# 网站标题
title: Lamirs ☆ Daze
# 网站副标题
subtitle: "帮助你学习高级程序设计语言"
# Sometimes your whole life boils down to one insame move      #详情
description: "愿青年摆脱了冷气,只是向前走！"
# 作者
author: yj2cs
# 语言
language: zh-CN
# 时区
timezone: UTC

# URL
# 注意，此选项一定要符合你实际的域名,影响gitalk的配置
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://lamirs.vercel.app # wugenqiang是我的账号，修改为自己的账号
root: /

# default ':year/:month/:day/:title/'
# ':year/:month/:day/:title/' | ':abbrlink' | ':url/' | <another link>
# 不带后缀名会导致有的web server(比如常见的GitHub pages)发送错误的MIME类型，浏览器接收到非HTML的MIME，会默认进行下载
# 所以，请带一个`/`后缀，或者以.html为后缀，即必须需要有后缀
permalink: ':slug/'
permalink_defaults:
  langu: cn # :langu -> cn (replace),
  #then you can write like this: permalink: :langu/:title/
  # in this,:langu will be replaced with cn

# 改写 permalink 的值来美化 URL
pretty_urls:
  # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_index: false
  # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
  trailing_html: false

#短链接
# package.json
#     "hexo-abbrlink": "^2.2.1",
# abbrlink:
#   alg: crc16 #算法： crc16(default) and crc32
#   rep: hex #进制： dec(default) and hex: dec #输出进制：十进制和十六进制，默认为10进制。丨dec为十进制，hex为十六进制

# Directory
source_dir: source
# source_dir: la-blog-source
public_dir: public
tag_dir: tags # 标签
archive_dir: archives # 归档
category_dir: categories # 类别
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - "_posts/Find unlinked files plugin output.md"
  - "Find unlinked files plugin output.md"

# Writing
# see https://hexo.io/zh-cn/docs/configuration.html
new_post_name: :title.md # File name of new posts
# 基本的页面，用来指定你文章的基本样式，不DIY的话请保持默认选项，
# 也可在*.md中提供 layout: 'shuoshuo' 这种方式指定其他单独的页面样式(需DIY)
default_layout: post
# Title case：特征就是句首字母大写，一些较「实」的词要首字母大写，而那些冠词、连词、介词、be 等较「虚」的词首字母不大写。但这界限的划分方式有很多种，是否要让 be 的各种形式首字母大写是最大的变数。Title case 也是常用于标题的。
titlecase: false # Transform title into titlecase
# 在新选项卡中打开外部链接
external_link: # Open external links in new tab
  enable: true
# filename_case	把文件名称转换为 (1) 小写或 (2) 大写
filename_case: 1
# 对草稿提供渲染 render_drafts	显示草稿
render_drafts: false
# 图片文件夹
post_asset_folder: true
# 注意：relative_link是 Jekyll 和 GitHub 都建议关闭的功能
# 默认情况下，Hexo 生成的超链接都是绝对地址。
# 例如，如果您的网站域名为 example.com,您有一篇文章名为 hello，
# 那么绝对链接可能像这样：http://example.com/hello.html，它是绝对于域名的。
# 相对链接像这样：/hello.html，也就是说，无论用什么域名访问该站点，都没有关系，
# 这在进行反向代理时可能用到。通常情况下，建议使用绝对地址。
relative_link: false
# 显示未来（Time）的文章
future: true

# 代码高亮
# highlight js 存在安全问题，现在替换为 hexo5开始支持的
highlight:
  # enable: true #next->true
  enable: false # highlight有安全风险，换成prismjs prismjs
  line_number: true
  # 自动检测
  auto_detect: false
  # 制表符替换
  tab_replace:

prismjs:
  enable: true
  preprocess: false
  line_number: true
  tab_replace: ''

# 站内搜索
# hexo-generator-searchdb
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# per_page应当与主题的设置相对应，有些主题设置中会有一个 类似homeArticleShown的选项
index_generator:
  path: ""
  per_page: 15
  order_by: -date

# hexo-generator-archive
# see https://github.com/hexojs/hexo-generator-archive
archive_generator:
  ##归档页面默认20篇文章标题
  per_page: 20
  ##生成年视图
  yearly: true
  ##生成月视图
  monthly: true

tag_generator:
  per_page: 15

# hexo-generator-category
# see https://github.com/hexojs/hexo-generator-category
category_generator:
  per_page: 10
  order_by: -date

# Category & Tag
default_category: article
category_map: categorys
tag_map: tags

# hexo-generator-feed
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# Date / Time format
# Hexo uses Moment.js to parse and display date
# You can customize the date format as defined in
# http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination 0关闭分页
per_page: 0
pagination_dir: page

# Extensions
# Plugins: https://hexo.io/plugins/
# Themes: https://hexo.io/themes/
# defaults: theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   # see https://hexo.io/docs/one-command-deployment#content-inner
#   type: git
#   #repository: https://github.com/wugenqiang/wugenqiang.github.io.git #复制过来
#   # github: https://github.com/yj2cs/yj2cs.github.io.git,master
#   #branch: master
#   repo:
#     github: https://github.com/YJ2CS/yj2cs.github.io.git,master
#     # coding: https://e.coding.net/yj2cs/o/yj2cs.coding.me.git,master
#     # gitee: https://gitee.com/wugenqiang/wugenqiang.git,master

# sitemap setting 用于搜索引擎扫描你的站点时，确定你站点的结构
# hexo-generator-sitemap
sitemap:
  path: sitemap.xml
# hexo-generator-baidu-sitemap
# baidusitemap:
#   path: baidusitemap.xml

# 标签云
#tag_cloud:
#  textFont: Trebuchet MS, Helvetica
#  textColor: '#fc6423'
#  textHeight: 17
#  outlineColor: '#b3e5ef'
#  maxSpeed: 0.07

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
## cn_Docs: https://markdown-it.docschina.org/api/MarkdownIt.html#markdownit-new
markdown:
  render:
    # false。设成 true 来启用在源码中(支持) HTML 标签。注意！这是不安全的！你可能需要额外的消毒剂(sanitizer)来组织来自 XSS 的输出。最好是通过插件来扩展特性，而不是启用 HTML。
    html: true
    # 设成 true 来给闭合的单个标签（<br />）添加 '/'。只有完全兼容 CommonMark 模式时才需要这样做。实际上你只需要 HTML 输出。
    xhtmlOut: false
    # 设成 true 来转化段落里的 \n 成 <br>
    breaks: true
    # 设成 true 来自动转化像 URL 的文本成链接。
    linkify: true
    # 设成 true 来启用某些语言中性的替换以及引号的美化（智能引号）。
    typographer: true
    # String 或 Array 类型。在 typographer 启用和支持智能引号时，进行双引号 + 单引号对替换。 比方说，
    # 你可以支持 '«»„“' 给俄罗斯人使用， '„“‚‘' 给德国人使用。
    # 还有 ['«\xA0', '\xA0»', '‹\xA0', '\xA0›']  给法国人使用（包括 nbsp）。
    quotes: "“”‘’"
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji # add emoji
    # 增加对wikilinks的解析支持
    # [[title home]] -> [title_home](...)
    - name: '@gerhobbelt/markdown-it-wikilinks'
      options:
        # deaault: linkPattern: /\[\[([^\x00-\x1f|]+?)(\|([\s\S]+?))?\]\]/,          // accept anything, except control characters (CR, LF, etc) or |
        # linkPattern: /\[\[([\w\s/\u4E00-\u9FA5A-Za-z0-9_\-#]+)(\|([\w\s/\u4E00-\u9FA5A-Za-z0-9_\-#]+))?\]\]/
        # 将所有 wiki 链接渲染为绝对链接。
        # 默认： false
        # 这项要根据你前面对链接的渲染设置来更改
        makeAllLinksAbsolute: true
        # 绝对链接的前缀
        # default: /
        # baseURL: 'https://lamirs.vercel.app/'
        # url的后缀,
        # default: .html
        # [[title home]] -> [title_home](...title_home/index.html),注意后缀从默认的.html更改为 /index.html
        # uriSuffix: '/index.html'
        uriSuffix: ''
    # - name: markdown-it-obsidian
    #   options:
    #     # deaault: linkPattern: /\[\[([^\x00-\x1f|]+?)(\|([\s\S]+?))?\]\]/,          // accept anything, except control characters (CR, LF, etc) or |
    #     # linkPattern: /\[\[([\w\s/\u4E00-\u9FA5A-Za-z0-9_\-#]+)(\|([\w\s/\u4E00-\u9FA5A-Za-z0-9_\-#]+))?\]\]/
    #     # 将所有 wiki 链接渲染为绝对链接。
    #     # 默认： false
    #     # 这项要根据你前面对链接的渲染设置来更改
    #     makeAllLinksAbsolute: true
    #     # 绝对链接的前缀
    #     # default: /
    #     # baseURL: 'https://lamirs.vercel.app/'
    #     # url的后缀,
    #     # default: .html
    #     # [[title home]] -> [title_home](...title_home/index.html),注意后缀从默认的.html更改为 /index.html
    #     # uriSuffix: '/index.html'
    #     uriSuffix: ''


  anchors:
    level: 1
    collisionSuffix: "v"
    # If `true`, creates an anchor tag with a permalink besides the heading.
    # 如果为“true”，则在标题旁边创建一个带有永久链接的定位标记。
    permalink: false
    permalinkClass: header-anchor
    # The symbol used to make the permalink
    # 用于生成永久链接的符号
    permalinkSymbol: ˃

server:
  port: 5000
  compress: true
  header: true

# 博客加上萌萌的宠物或萌妹子
# Live2D
# https://github.com/EYHN/hexo-helper-live2d
# live2d:
#   enable: true
  # enable: false
  # scriptFrom: local # 默认
    # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js # 你的自定义 url
  # pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  # pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  # pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  # debug: false # 调试, 是否在控制台输出日志
  # model:
    # use: live2d-widget-model-koharu
    # use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
# -------------------------------------------------------------------
    # Live2D General Settings
    ## https://github.com/xiazeyu/live2d-widget.js
    ## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
    # scale: 1
    # hHeadPos: 0.5
    # vHeadPos: 0.618
  # display:
  #   superSample: 2
  #   width: 75
  #   height: 150
  #   # position: right
  #   position: 'left'
  #   hOffset: 0
  #   vOffset: -20
  # mobile:
  #   show: false
  #   scale: 0.5
  # react:
  #   opacityDefault: 0.7
  #   opacityOnHover: 0.2




# 自动摘录
# 本插件通过注册generator对所有文章在生成的时候进行处理，
# 如果文章内容含有10个一级html标签，那么取这10个做为列表页面摘要，否则全部显示。
# 您可以通过在配置中设置深度（默认值为 10）来指定摘录的大小。
# 还可以使用 css 选择器从生成的摘录中排除某些标记。将排除与任何选择器匹配的标记。
# 默认行为 hideWholePostExcerpts: false 是只显示摘录，如果它不会是整个职位。设置为覆盖它，并显示整个帖子摘录。
excerpt:
  depth: 10
  excerpt_excludes: [ ]
  more_excludes: [ ]
  hideWholePostExcerpts: true

# 下面这种做法在next7.6版本后已经不再支持
# Automatically Excerpt. Not recommend.
# Use <!-- more --> in the post to control excerpt accurately.
## 自动摘录，开启，暂时没发现bug
#auto_excerpt:
#  enable: true
#  length: 150
#  # Automatically scroll page to section which is under <!-- more --> mark.
#  scroll_to_more: true
